members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('login_user', views.login_user, name="login_u")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from polls import views

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /pools/users/
    path('users/', views.users, name = 'users'),
    path('result', views.result, name = 'result'),
    path('results_all', views.results_all, name = 'results_all')
]

members/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    correct = models.BooleanField(default=False)
    def __str__(self):
        return self.choice_text

class User(models.Model):
    name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    age = models.IntegerField(default=0)
    username = models.CharField(max_length=200, null=True)
    score = models.IntegerField(default=0, null=True)
    def __str__(self):
        return self.name + " " + self.last_name
       

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect(reverse('polls:index'))
        else:
            # Return an 'invalid login' error message.
            messages.success(request, ("There was an error"))
            return redirect('login_u')
    return render(request, 'registration/login.html', {})   

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, User, Choice
import random


def index(request):
    
    latest_question_list = Question.objects.all()

    answear_list = list(Choice.objects.all())
    random.shuffle(answear_list)
    context = {'latest_question_list': latest_question_list, 'answear_list': answear_list}

    points = 0
    if request.method == "POST":
        print(request.POST)
        if request.POST.get("save"):
            for item in answear_list:
                if request.POST.get("c" + str(item.id)) == "clicked":
                    item.votes += 1
                    if item.correct == True:
                        points += 1
                item.save()
        if request.user.is_authenticated:
            if User.objects.filter(username=request.user.username).exists():
                tempUser = User.objects.filter(username=request.user.username).get()
                tempUser.score = points
                tempUser.save()
        request.session['score'] = points

        # return render(request, 'polls/result.html', {'score' : points})
        return HttpResponseRedirect(reverse('polls:result'))

    return render(request, 'polls/index.html', context)

def results_all(request):
    if request.user.is_superuser:
        users_results = User.objects.all()
        return render(request, 'polls/all_results.html', {'users_results' : users_results})
    return HttpResponse("You are not authorized")

def result(request):
    if 'score' in request.session:
        points = request.session['score']
    else:
        points = 0
    return render(request, 'polls/result.html', {'score' : points})

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def users(request):
    user_list = User.objects.all()
    return render(request, 'polls/users.html', {'user_list': user_list})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/all_results.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="text-center">
    <h1>Test Results</h1>
        <div class="text-center mx-5"
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Age</th>
                        <th scope="col">Score</th>
                    </tr>
                </thead>
                <tbody>
                    {% if users_results %}
                        {% for user in users_results %}
                            <tr>
                                <th scope="row"> {{user.name}}</th>
                                <td> {{user.last_name}}</td>
                                <td> {{user.age}}</td>
                                <td> {{user.score}}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <p>Empty</p>
                    {% endif %}
                </tbody>
            </table>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a class="btn btn-primary" href="{% url 'polls:index' %}" role="button">Back</a>
            </div>
        </div>
    
</div>
{% endblock content %}

polls/templates/polls/base.html
{% load static %}
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <title>First site</title>
	<link rel="stylesheet" href="{% static 'style.css' %}"/>
    </head>
    <body>
    <div>
	<header>
		<nav>
		    <ul class="nav-links">
			<li><a href="\">QUIZ</a></li>
			<li><a href="{% url 'polls:result' %}">MY SCORE</a></li>
			{% if user.is_authenticated %}
				{% if user.is_superuser %}
				<li><a href="{% url 'polls:results_all' %}">RESULTS</a></li>
				{% endif %}
			{% endif %}
		    </ul>
		</nav>
		<div class="nav-right">
		{% if user.is_authenticated %}
		Hi {{ user.username }}!
		 <a class="cta" href="\accounts\logout"><button>Log out</button></a>
		      {% else %}
		 You are not logged in.
       		 <a class="cta" href="{% url 'members:login_u' %}"><button>Login</button></a>
	      {% endif %}
		</div>
    </header>
    {% block content %}
    {% endblock content %}
    </div>
  </body>
    
</html>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}

<div class="text-center">
    <h2>QUIZ</h2>
</div>
    <form class="mx-3" method="post" action="#">
	{% csrf_token %}
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	{% if latest_question_list %}
	<ul>
	    {% for question in latest_question_list %}
	    <li>{{ question.question_text }}</li>
		<ul>
		{% for answear in answear_list %}
		    {% if answear.question_id == question.id %}
			<div class="mb-3 form-check">
			    <input type="checkbox" class="form-check-input" value="clicked" name="c{{ answear.id }}">{{answear.choice_text}}
			    {% comment %} <label class="form-check-label" for="c{{ answear.id }}">{{answear.choice_text}}</label> {% endcomment %}
			</div>
		    {% endif %}
		{% endfor %}
		</ul>
	    {% endfor %}
	</ul>
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
	<div class="text-center " style="padding: 50px 0;">
	    <button type="sumbit"  name="save" value="save">Sumbit</button>
	</div>
    </form>
{% endblock content %}

polls/templates/polls/result.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="text-center">
    <h1> Your score: {{score}}<h1>
</div>

{% endblock content %}

polls/templates/polls/results.html
{% extends 'base.html' %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/users.html
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

        
    </head>
    
    <body>
        <div class="text-center mx-5"
            <h2>users</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Age</th>
                    </tr>
                </thead>
                <tbody>
                    {% if user_list %}
                        {% for user in user_list %}
                            <tr>
                                <th scope="row">{{user.id}}</th>
                                <td> {{user.name}}</td>
                                <td> {{user.last_name}}</td>
                                <td> {{user.age}}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <p>Empty</p>
                    {% endif %}
                </tbody>
            </table>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a class="btn btn-primary" href="/polls" role="button">Back</a>
            </div>
        </div>
    </body>
</html>